language: node_js
node_js:
  - '8'
  - '6'
  - '4'
install:
  - npm install -g npx
  - npx yarn install
  - npx lerna bootstrap
  - npm --version
  - yarn --version
  - npx --version
script:
  - npx yarn build
  - npx yarn test
