language: node_js
node_js:
  - '8'
  - '6'
  - '4'
install:
  - npm install -g npx
  - npx yarn install
  - npx lerna bootstrap --since $TRAVIS_BRANCH --include-filtered-dependencies --stream
  - npm --version
  - yarn --version
  - npx --version
script:
  - npx yarn build --since $TRAVIS_BRANCH --include-filtered-dependencies --stream
  - npx yarn lint --since $TRAVIS_BRANCH --include-filtered-dependencies --stream
  - npx yarn deps --since $TRAVIS_BRANCH --include-filtered-dependencies --stream
  - npx yarn test --since $TRAVIS_BRANCH --include-filtered-dependencies --stream
