language: node_js
node_js:
  - '8'
  - '6'
  - '4'
install:
  - npm install -g npx
  - npx yarn install
  - npx lerna bootstrap --since origin/master --include-filtered-dependencies --stream
  - npm --version
  - yarn --version
  - npx --version
script:
  - npx yarn build --since origin/master --include-filtered-dependencies --stream
  - npx yarn lint --since origin/master --include-filtered-dependencies --stream
  - npx yarn deps --since origin/master --include-filtered-dependencies --stream
  - npx yarn test --since origin/master --include-filtered-dependencies --stream
