language: node_js
node_js:
  - '8'
  - '6'
  - '4'
install:
  - npm install -g npx
  - npx yarn install
  - $(npm bin)/lerna bootstrap
  - npm --version
  - yarn --version
  - npx --version
  - $(npm bin)/lerna --version
script:
  - npx yarn build
  - npx yarn test
