language: node_js
node_js:
  - '7'
  - '6'
  - '4'
before_install:
  - git fetch --unshallow
before_script:
  - conventional-changelog-lint --from=$TRAVIS_BRANCH --to=$TRAVIS_PULL_REQUEST_BRANCH
  - npm run build
script:
  - npm test
